### ISSUE TITLE
Missing openldap_cluster_status.conf

### ISSUE THREAD

**Issue by rgarrigue** [MrCirca/OpenLDAP-Cluster-Zabbix#1]
Hi

> Put openldap_cluster_status.conf in /etc/zabbix/zabbix_agentd.conf.d directory in LDAP Consumer.

This conf file is missing from the repo :-)

**Comment by MrCirca** [comment]
Oh  i am sorry!

**Comment by MrCirca** [comment]
Now it's ok, but you have to change script path

**Comment by rgarrigue** [comment]
Thanks
